language: node_js
node_js:
  - "lts/*"

services: mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - export MONGODB_FEATHERS_REALWORLD="mongodb://travis:test@127.0.0.1:27017/mydb_test"
